markdown: kramdown
highlighter: pygments

name: Wizacha Tech-Side
wizacha: "<a href='https://wizacha.com'>Wizacha</a>"
github_blog_url: "https://github.com/wizacha/wizacha.github.io/blob/master/"
hostname: wizacha.github.io
